### ISSUE TITLE
Versions above 1.21.0 will not produce IR Images

### ISSUE THREAD

**Issue by TheMetMan** [pytroll/trollimage#162] opened 2024-02-13 10:05 UTC
**Describe the bug**
I am decoding MSG Data using SatPy
I upgrade to SatPy 0.46.0 and all the modules in the virtual environment to the latest versions. After that all my images with IR in them would not render, they are just blank.
In particular 'natural_color_with_night_ir' only shows daylight image, not Night. So decoding an image at 0800 hrs of the Eastern Atlantic the cloud in the night part of the image is missing.
After a lot of research I discovered that the problem is with trollimage. Versions above 1.21.0 will not render IR.
**To Reproduce**

**Expected behavior**
The image should show the cloud structure for daylight and nighttime.

**Actual results**
I attach two images to show the difference. The IR part of the image should be rendered, but it is not.

**Environment Info:**
 - OS: Gentoo Linux
 - Satpy Version: [e.g. 0.46.0]
![correct_0800_natural_color_with_night_ir](https://github.com/pytroll/trollimage/assets/6077253/994b96de-056f-4c36-8d40-773a19c02fbe)
![incorrect_0800_natural_color_with_night_ir](https://github.com/pytroll/trollimage/assets/6077253/6d6022c0-48ca-451d-a83b-b6141f71a868)

**Comment by pnuu** [comment] 2024-02-13 10:08
There's nothing IR-specific in Trollimage. Could you share a minimal script that reproduces the issue you're seeing?

**Comment by mraspaud** [comment] 2024-02-13 10:11
Looks like the stretching is not behaving correctly: greenland is blue and the day part also has funky colours.

**Comment by TheMetMan** [comment] 2024-02-13 12:37
OK, I am not the only one with this problem, have a  look at [this link](https://groups.io/g/MSG-1/topic/satpy_upgrade_causing_me/104294436?p=,,,20,0,0,0::recentpostdate/sticky,,,20,2,0,104294436,previd%3D1707821000815730036,nextid%3D1704977503032417507&previd=1707821000815730036&nextid=1704977503032417507) from the Group for Earth Observation MSG 

Attached is the Python script to create the above image, my areas yaml file and the list of modules in my Python venv using Python 3.11.7 All the modules are up to date as the latest except trollimage.

[msg1_no_comments.py.txt](https://github.com/pytroll/trollimage/files/14261624/msg1_no_comments.py.txt)
[fg_areas.yaml.txt](https://github.com/pytroll/trollimage/files/14261626/fg_areas.yaml.txt)
[modules_list.txt](https://github.com/pytroll/trollimage/files/14261629/modules_list.txt)

**Comment by pnuu** [comment] 2024-02-13 13:00
Smells like a problem in stretching integer data as this happens only(?) when using a static background image.

**Comment by djhoese** [comment] 2024-02-13 19:23
Looking at the second image in the original post I see that the land on the night side still has valid data. The sea/ocean is the only part that seems to be pure black. The `night_ir_with_background` is a combination of `night_ir_alpha` and `_night_background`. When I load just `_night_background` I don't see any issues (I think). I'll have to track down some SEVIRI data on my computer tonight or tomorrow. Not sure I'll have time this afternoon.

**Comment by djhoese** [comment] 2024-02-13 19:25
Ah here we go, why is `night_ir_alpha` using a dynamic stretch as its enhancement:

```
  night_ir_alpha:
    standard_name: night_ir_alpha
    operations:
    - name: stretch
      method: !!python/name:satpy.enhancements.stretch
      kwargs: {stretch: linear, cutoffs: [0.02, 0.02]}
    - name: inverse
      method: !!python/name:satpy.enhancements.invert
      args:
      - [true, true, true, true]
```

If I recall correctly that's exactly what @mraspaud assumed would never be done in #145.

**Comment by mraspaud** [comment] 2024-02-13 20:10
Ok, I'll have a look in the morning

**Comment by mraspaud** [comment] 2024-02-14 10:20
@TheMetMan I just created PR #163, which should address part of the problem, the other part being in satpy. I will fix the corresponding satpy recipes once this is merged, but if you want to try it out, in satpy's `enhancements/generic.yaml`, we should have 
```yaml
  night_ir_alpha:
    standard_name: night_ir_alpha
    operations:
    - name: stretch
      method: !!python/name:satpy.enhancements.stretch
      kwargs: {stretch: linear, cutoffs: [[0.02, 0.02], [0.02, 0.02], [0.02, 0.02], [0.02, 0.02]]}
    - name: inverse
      method: !!python/name:satpy.enhancements.invert
      args:
      - [true, true, true, true]
```

Using this, I get the expected image.

**Comment by TheMetMan** [comment] 2024-02-14 10:54
OK, I have changed the `enhancements/generic.yaml` file as you suggest, but I get the following error:

```
Traceback (most recent call last):
  File "/home/francis/FG-Docs/PycharmProjects/Py_MeteosatImageCreator_2/src/msg1_no_comments.py", line 68, in <module>
    compute_writer_results(results)
  File "/home/francis/bin/Python3_11Environments/Py_SatPy_Generic/lib/python3.11/site-packages/satpy/writers/__init__.py", line 594, in compute_writer_results
    da.compute(delayeds)
  File "/home/francis/bin/Python3_11Environments/Py_SatPy_Generic/lib/python3.11/site-packages/dask/base.py", line 663, in compute
    results = schedule(dsk, keys, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/francis/bin/Python3_11Environments/Py_SatPy_Generic/lib/python3.11/site-packages/trollimage/xrimage.py", line 1010, in _compute_quantile
    left, right = data_arr.quantile([cutoffs[0], 1. - cutoffs[1]], dim=['x', 'y'])
                                                 ~~~^~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'float' and 'list'
```
I am using the same script I have uploaded above It happens on the line:

`compute_writer_results(results)`

**Comment by pnuu** [comment] 2024-02-14 10:58
Did you also install the Trollimage version from #163 that adds the handling for the new limits?

**Comment by pnuu** [comment] 2024-02-14 11:01
```bash
pip install git+https://github.com/mraspaud/trollimage.git@fix-alpha-stretching
```
should install the version on the PR.

**Comment by TheMetMan** [comment] 2024-02-14 11:49
Sorry@mraspaud My error, I have installed trollimage 1.22.2 and then the patch as above and all well now.

**Comment by mraspaud** [comment] 2024-02-14 11:50
@TheMetMan thanks a lot for checking this out!

**Closed** 2024-02-14 16:11 UTC
Labels: bug
